### ISSUE TITLE
Given scopes were invalid.

### ISSUE THREAD

**Issue by tabatadzem** [fschutte/ING-API-Showcase#2]
Hi, for me oAuth returns with an error:

OAuth response status = 400 
```
{
  "message" : "Given scopes were invalid."
}
```

When I cut the scope from body `grant_type=client_credentials` ~~&scope=greetings%3Aview~~, then the oAuth returns 200 OK, but the Greetings response status = 401 Unauthorized...

I have subscribed on Greetings API, maybe it is on ING side?

**Comment by fschutte** [comment]
In the ING developer portal in your app, so you see that you are subscribed to the showcase API and is the status 'Approved'?
![image](https://user-images.githubusercontent.com/490486/59152520-ee7c2280-8a45-11e9-8191-7d1de07ce0f7.png)



BTW: I just did some tests, and it seems to work fine even if I leave out the scope. However, if I put in a scope for which I have not subscribed, or a random made-up scope, then I also get the 400.

**Comment by tabatadzem** [comment]
Thank you for response, you are right, the status of API was the reason. In my account it is still pending
<img width="924" alt="Schermafbeelding 2019-06-09 om 09 29 31" src="https://user-images.githubusercontent.com/27767849/59156315-6162b900-8a99-11e9-95ea-2f8c240c1930.png">
How long does it take for approval?

By the way, in my API Marketplace I can subscribe only for Showcase API, all other API's simply does not have the **Subscribe** button...

**Comment by fschutte** [comment]
Yes, the Showcase is the only one accessible. The others are either not yet available or only accessible for accredited PSD2 parties.
As far as the Status Pending: I can't remember how long it took, but the whole process, including support and such, was quite slow.  Could take a few days even.  Let me know once it is Approved and it works!
